pipeline {
    agent any

    environment {
        VENV = 'myenv'
        DOCKER_IMAGE = 'hildaenyioko/messaging_app:latest'
    }

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Hilda-Enyioko/alx-backend-python.git',
                    credentialsId: 'github-creds'
            }
        }

        stage('Install Python') {
            steps {
                sh '''
                apt-get update
                apt-get install -y python3 python3-venv python3-pip
                '''
            }
        }

        stage('Set Up Python Environment') {
            steps {
                sh '''
                python3 -m venv $VENV
                . $VENV/bin/activate
                pip3 install --upgrade pip
                pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                . $VENV/bin/activate
                pytest messaging_app/tests \
                  --junitxml=messaging_app/test-report.xml
                '''
            }
        }

        // New stages for Docker build and push
        stage('Build Docker Image') {
            steps {
                sh '''
                docker build -t $DOCKER_IMAGE messaging_app/
                '''
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    docker push $DOCKER_IMAGE
                    '''
                }
            }
        }
    }

    post {
        always {
            junit 'messaging_app/test-report.xml'
        }
    }
}
